import {
  type ExtensionAPI,
} from "@earendil-works/pi-coding-agent";
import {
  createSettings,
  isInstallTelemetryEnabled,
  loadConfig,
  parseModelReference,
} from "./config.js";
import { compactWithOneRetry } from "./retry.js";

function warn(message: string, error?: unknown): void {
  if (error === undefined) {
    console.warn(`[pi-compaction-model] ${message}`);
  } else {
    console.warn(`[pi-compaction-model] ${message}`, error);
  }
}

const OPENROUTER_ATTRIBUTION_HEADERS = {
  "HTTP-Referer": "https://pi.dev",
  "X-OpenRouter-Title": "pi",
  "X-OpenRouter-Categories": "cli-agent",
} as const;

/** Add the same gated OpenRouter app attribution as Pi's normal request path. */
export function withOpenRouterAttribution(
  model: { provider: string; baseUrl: string },
  telemetryEnabled: boolean,
  headers: Record<string, string> | undefined,
): Record<string, string> | undefined {
  if (!telemetryEnabled) return headers;
  const isOpenRouter =
    model.provider === "openrouter" || model.baseUrl.includes("openrouter.ai");
  if (!isOpenRouter) return headers;
  return { ...OPENROUTER_ATTRIBUTION_HEADERS, ...headers };
}

/**
 * Hook-provided compactions are marked as extension-generated by Pi. Native
 * preparation intentionally does not trust arbitrary extension details, so it
 * will not carry their file lists into a later compaction. Since this extension
 * returns Pi's own details shape, restore those lists before calling native
 * compact() again. Sets make this harmless for native previous entries too.
 */
function restorePreviousFileOperations(
  preparation: {
    fileOps: { read: Set<string>; edited: Set<string> };
  },
  branchEntries: Array<{ type: string; details?: unknown }>,
): void {
  const previous = [...branchEntries].reverse().find((entry) => entry.type === "compaction");
  if (!previous || typeof previous.details !== "object" || previous.details === null) return;

  const details = previous.details as {
    readFiles?: unknown;
    modifiedFiles?: unknown;
  };

  if (Array.isArray(details.readFiles)) {
    for (const path of details.readFiles) {
      if (typeof path === "string") preparation.fileOps.read.add(path);
    }
  }

  if (Array.isArray(details.modifiedFiles)) {
    for (const path of details.modifiedFiles) {
      if (typeof path === "string") preparation.fileOps.edited.add(path);
    }
  }
}

export default function compactionModel(pi: ExtensionAPI): void {
  pi.on("session_before_compact", async (event, ctx) => {
    restorePreviousFileOperations(event.preparation, event.branchEntries);

    const settings = createSettings(ctx);
    const config = loadConfig(ctx, settings);
    if (!config || !config.reasons.includes(event.reason)) return;

    const reference = parseModelReference(config.model);
    if (!reference) {
      warn(`Invalid model '${config.model}'; expected provider/model. Using Pi's active model.`);
      return;
    }

    const model = ctx.modelRegistry.find(reference.provider, reference.modelId);
    if (!model) {
      warn(`Model not found: ${config.model}. Using Pi's active model.`);
      return;
    }

    try {
      const auth = await ctx.modelRegistry.getApiKeyAndHeaders(model);
      if (!auth.ok) {
        warn(`Authentication failed for ${config.model}: ${auth.error}. Using Pi's active model.`);
        return;
      }

      // Older Pi declarations do not expose credential-specific endpoints.
      const authBaseUrl = "baseUrl" in auth && typeof auth.baseUrl === "string"
        ? auth.baseUrl
        : undefined;
      const requestModel = authBaseUrl ? { ...model, baseUrl: authBaseUrl } : model;

      // Match Pi's native compaction bridge: null marks a deleted header.
      const authHeaders = auth.headers
        ? Object.fromEntries(
            Object.entries(auth.headers).filter((entry): entry is [string, string] => entry[1] !== null),
          )
        : undefined;
      const headers = withOpenRouterAttribution(
        requestModel,
        isInstallTelemetryEnabled(settings),
        authHeaders,
      );

      const result = await compactWithOneRetry(
        event.preparation,
        requestModel,
        auth.apiKey,
        headers,
        event.customInstructions,
        event.signal,
        config.thinkingLevel,
        undefined,
        auth.env,
      );

      return { compaction: result };
    } catch (error) {
      if (event.signal.aborted || (error instanceof Error && error.name === "AbortError")) {
        return { cancel: true };
      }
      warn(`Compaction with ${config.model} failed; using Pi's active model.`, error);
      return;
    }
  });
}

export {
  COMPACTION_REASONS,
  THINKING_LEVELS,
  parseModelReference,
  resolveConfig,
  type CompactionModelConfig,
  type CompactionReason,
  type ThinkingLevel,
} from "./config.js";
